// Process ONE couple's photos into web-ready variants and MERGE them into
// the existing manifest — without touching the other couples.
//
// Unlike process-photos.mjs (which scans the whole shared drive and
// regenerates the entire manifest), this targets a single source folder and
// a single couple slug, so it's safe to run for a one-off addition such as a
// new pre-wedding / engagement gallery.
//
// Usage:
//   node scripts/process-couple.mjs \
//     --slug eric-cassandra \
//     --name "Eric & Cassandra" \
//     --src "Z:/Mi unidad/Fotos Compartides Objectiu/Fotos Web Lifetime Weddings/Pedida de mano"
//
// Notes:
//   • Images are numbered 001, 002, … in filename order. Pass --sort name
//     (default) or --sort mtime to control the order.
//   • Output: public/photos/<slug>/*.jpg  +  merged src/data/photos.generated.ts
//   • Re-running replaces just this couple's entry in the manifest.

import { readdir, stat, mkdir, writeFile, readFile } from 'node:fs/promises';
import { join, basename } from 'node:path';
import sharp from 'sharp';

const OUT = 'public/photos';
const MANIFEST = 'src/data/photos.generated.ts';

const SIZES = [
  { label: 'sm', width: 640, quality: 80 },
  { label: 'md', width: 1200, quality: 82 },
  { label: 'lg', width: 1920, quality: 84 },
];

// ── args ──────────────────────────────────────────────────────────
function getArg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}
const slug = getArg('slug');
const name = getArg('name', null);
const src = getArg('src');
const sortBy = getArg('sort', 'name');
if (!slug || !src) {
  console.error('Missing required args. Example:\n  node scripts/process-couple.mjs --slug eric-cassandra --name "Eric & Cassandra" --src "Z:/…/Pedida de mano"');
  process.exit(1);
}

async function ensureDir(d) { try { await mkdir(d, { recursive: true }); } catch {} }

async function listImages(dir) {
  const out = [];
  for (const e of await readdir(dir)) {
    const p = join(dir, e);
    const s = await stat(p);
    if (s.isFile() && /\.(jpe?g)$/i.test(e)) out.push({ path: p, mtime: s.mtimeMs });
  }
  if (sortBy === 'mtime') out.sort((a, b) => a.mtime - b.mtime);
  else out.sort((a, b) => basename(a.path).localeCompare(basename(b.path), undefined, { numeric: true }));
  return out.map((o) => o.path);
}

async function processImage(input, index) {
  const outDir = join(OUT, slug);
  await ensureDir(outDir);
  const stem = String(index).padStart(3, '0');
  const meta = { id: `${slug}/${stem}`, couple: slug, variants: {} };

  const { width, height } = await sharp(input, { failOn: 'none' }).rotate().metadata();
  meta.width = width ?? 0;
  meta.height = height ?? 0;
  meta.orientation = width && height ? (width >= height ? 'landscape' : 'portrait') : 'square';

  for (const s of SIZES) {
    const jpg = `${stem}-${s.label}.jpg`;
    const webp = `${stem}-${s.label}.webp`;
    await sharp(input, { failOn: 'none' })
      .rotate()
      .resize({ width: s.width, withoutEnlargement: true })
      .jpeg({ quality: s.quality, progressive: true, mozjpeg: true })
      .toFile(join(outDir, jpg));
    // Also emit a matching .webp (the site serves <source type="image/webp">).
    await sharp(input, { failOn: 'none' })
      .rotate()
      .resize({ width: s.width, withoutEnlargement: true })
      .webp({ quality: s.quality })
      .toFile(join(outDir, webp));
    meta.variants[s.label] = `/photos/${slug}/${jpg}`;
  }
  return meta;
}

// ── read existing manifest so we merge instead of overwrite ─────────
async function readManifest() {
  try {
    const raw = await readFile(MANIFEST, 'utf-8');
    const start = raw.indexOf('=', raw.indexOf('export const PHOTOS'));
    const json = raw.slice(start + 1, raw.lastIndexOf(';')).trim();
    return JSON.parse(json);
  } catch {
    return {};
  }
}

const files = await listImages(src);
console.log(`Found ${files.length} source photos in ${src}`);

const images = [];
let i = 0;
for (const file of files) {
  try {
    images.push(await processImage(file, i + 1));
    process.stdout.write('.');
    i++;
  } catch (err) {
    console.error(`\n✗ ${file}:`, err.message);
  }
}
console.log(`\n✓ ${images.length} processed → ${join(OUT, slug)}`);

const manifest = await readManifest();
manifest[slug] = { couple: name, images };

const body = `// Generated by scripts/process-photos.mjs — do NOT edit by hand.
// Re-run the script when new source photos are added.

export interface PhotoVariant { sm: string; md: string; lg: string }
export interface Photo {
  id: string;
  couple: string; // couple slug
  width: number;
  height: number;
  orientation: 'landscape' | 'portrait' | 'square';
  variants: PhotoVariant;
}
export interface PhotoSet {
  couple: string | null; // display name
  images: Photo[];
}

export const PHOTOS: Record<string, PhotoSet> = ${JSON.stringify(manifest, null, 2)};
`;

await ensureDir('src/data');
await writeFile(MANIFEST, body, 'utf-8');
console.log(`✓ Merged '${slug}' into ${MANIFEST} (${Object.keys(manifest).length} couples total)`);
