// Read original wedding photos from the shared drive, resize to web-friendly
// sizes, organise by couple, and emit a JSON manifest for the site to consume.
//
// Usage: node scripts/process-photos.mjs
//
// Output: public/photos/<couple>/*.jpg  +  src/data/photos.generated.ts

import { readdir, stat, mkdir, writeFile } from 'node:fs/promises';
import { join, extname, basename } from 'node:path';
import sharp from 'sharp';

const SRC = 'F:/Mi unidad/Fotos Compartides Objectiu/Fotos Web Lifetime Weddings';
const OUT = 'public/photos';
const MANIFEST = 'src/data/photos.generated.ts';

// Map filename prefixes → clean slug. "pre_" and "preboda_" variants fall under
// the same couple so we don't split their galleries.
const COUPLE_MAP = [
  { pattern: /^Aaron&Marta/i, slug: 'aaron-marta', couple: 'Aaron & Marta' },
  { pattern: /^Cristina_Daniel/i, slug: 'cristina-daniel', couple: 'Cristina & Daniel' },
  { pattern: /^Idoya&Pau/i, slug: 'idoya-pau', couple: 'Idoya & Pau' },
  { pattern: /^Javi&Olaya/i, slug: 'javi-olaya', couple: 'Javi & Olaya' },
  { pattern: /^Jennifer&Albert/i, slug: 'jennifer-albert', couple: 'Jennifer & Albert' },
  { pattern: /^Jordi_Elena/i, slug: 'elena-jordi', couple: 'Elena & Jordi' },
  { pattern: /^(Pre_)?Josep&Eli/i, slug: 'josep-eli', couple: 'Elisabet & Josep' },
  { pattern: /^Pre_Josep_Eli/i, slug: 'josep-eli', couple: 'Elisabet & Josep' },
  { pattern: /^(Preboda_)?Marta_(i )?Adri/i, slug: 'marta-adria', couple: 'Marta & Adrià' },
];

const SIZES = [
  { label: 'sm', width: 640, quality: 80 },
  { label: 'md', width: 1200, quality: 82 },
  { label: 'lg', width: 1920, quality: 84 },
];

async function listFiles(dir) {
  const out = [];
  for (const e of await readdir(dir)) {
    const p = join(dir, e);
    const s = await stat(p);
    if (s.isFile() && /\.(jpe?g)$/i.test(e)) out.push(p);
  }
  return out;
}

function classify(filename) {
  const base = basename(filename);
  for (const m of COUPLE_MAP) {
    if (m.pattern.test(base)) return { slug: m.slug, couple: m.couple };
  }
  return { slug: 'generic', couple: null };
}

async function ensureDir(d) { try { await mkdir(d, { recursive: true }); } catch {} }

async function processImage(input, coupleSlug, index) {
  const outDir = join(OUT, coupleSlug);
  await ensureDir(outDir);
  const stem = String(index).padStart(3, '0');
  const meta = { id: `${coupleSlug}/${stem}`, couple: coupleSlug, variants: {} };

  const src = sharp(input, { failOn: 'none' }).rotate(); // respect EXIF orientation
  const { width, height } = await src.metadata();
  meta.width = width ?? 0;
  meta.height = height ?? 0;
  meta.orientation = width && height ? (width >= height ? 'landscape' : 'portrait') : 'square';

  for (const s of SIZES) {
    const file = `${stem}-${s.label}.jpg`;
    const out = join(outDir, file);
    await sharp(input, { failOn: 'none' })
      .rotate()
      .resize({ width: s.width, withoutEnlargement: true })
      .jpeg({ quality: s.quality, progressive: true, mozjpeg: true })
      .toFile(out);
    meta.variants[s.label] = `/photos/${coupleSlug}/${file}`;
  }
  return meta;
}

const files = await listFiles(SRC);
console.log(`Found ${files.length} source photos`);

const grouped = {};
for (const f of files) {
  const { slug, couple } = classify(f);
  grouped[slug] ??= { couple, photos: [] };
  grouped[slug].photos.push(f);
}

const manifest = {};
for (const [slug, g] of Object.entries(grouped)) {
  console.log(`\n▶ ${slug} (${g.photos.length} photos)`);
  const images = [];
  let i = 0;
  for (const file of g.photos) {
    try {
      const m = await processImage(file, slug, i + 1);
      images.push(m);
      process.stdout.write('.');
      i++;
    } catch (err) {
      console.error(`\n✗ ${file}:`, err.message);
    }
  }
  manifest[slug] = { couple: g.couple, images };
  console.log(` ✓ ${images.length} processed`);
}

// Emit TS manifest
const body = `// Generated by scripts/process-photos.mjs — do NOT edit by hand.
// Re-run the script when new source photos are added.

export interface PhotoVariant { sm: string; md: string; lg: string }
export interface Photo {
  id: string;
  couple: string; // couple slug
  width: number;
  height: number;
  orientation: 'landscape' | 'portrait' | 'square';
  variants: PhotoVariant;
}
export interface PhotoSet {
  couple: string | null; // display name
  images: Photo[];
}

export const PHOTOS: Record<string, PhotoSet> = ${JSON.stringify(manifest, null, 2)};
`;

await ensureDir('src/data');
await writeFile(MANIFEST, body, 'utf-8');
console.log(`\n✓ Wrote ${MANIFEST}`);
console.log(`✓ Processed ${Object.values(manifest).reduce((n, g) => n + g.images.length, 0)} photos total`);
