// Generated by scripts/process-photos.mjs — do NOT edit by hand.
// Re-run the script when new source photos are added.

export interface PhotoVariant { sm: string; md: string; lg: string }
export interface Photo {
  id: string;
  couple: string; // couple slug
  width: number;
  height: number;
  orientation: 'landscape' | 'portrait' | 'square';
  variants: PhotoVariant;
}
export interface PhotoSet {
  couple: string | null; // display name
  images: Photo[];
}

export const PHOTOS: Record<string, PhotoSet> = {
  "cristina-daniel": {
    "couple": "Cristina & Daniel",
    "images": [
      {
        "id": "cristina-daniel/001",
        "couple": "cristina-daniel",
        "variants": {
          "sm": "/photos/cristina-daniel/001-sm.jpg",
          "md": "/photos/cristina-daniel/001-md.jpg",
          "lg": "/photos/cristina-daniel/001-lg.jpg"
        },
        "width": 3943,
        "height": 5916,
        "orientation": "portrait"
      },
      {
        "id": "cristina-daniel/002",
        "couple": "cristina-daniel",
        "variants": {
          "sm": "/photos/cristina-daniel/002-sm.jpg",
          "md": "/photos/cristina-daniel/002-md.jpg",
          "lg": "/photos/cristina-daniel/002-lg.jpg"
        },
        "width": 3730,
        "height": 5594,
        "orientation": "portrait"
      },
      {
        "id": "cristina-daniel/003",
        "couple": "cristina-daniel",
        "variants": {
          "sm": "/photos/cristina-daniel/003-sm.jpg",
          "md": "/photos/cristina-daniel/003-md.jpg",
          "lg": "/photos/cristina-daniel/003-lg.jpg"
        },
        "width": 3915,
        "height": 5873,
        "orientation": "portrait"
      },
      {
        "id": "cristina-daniel/004",
        "couple": "cristina-daniel",
        "variants": {
          "sm": "/photos/cristina-daniel/004-sm.jpg",
          "md": "/photos/cristina-daniel/004-md.jpg",
          "lg": "/photos/cristina-daniel/004-lg.jpg"
        },
        "width": 3910,
        "height": 5866,
        "orientation": "portrait"
      },
      {
        "id": "cristina-daniel/005",
        "couple": "cristina-daniel",
        "variants": {
          "sm": "/photos/cristina-daniel/005-sm.jpg",
          "md": "/photos/cristina-daniel/005-md.jpg",
          "lg": "/photos/cristina-daniel/005-lg.jpg"
        },
        "width": 2542,
        "height": 3813,
        "orientation": "portrait"
      },
      {
        "id": "cristina-daniel/006",
        "couple": "cristina-daniel",
        "variants": {
          "sm": "/photos/cristina-daniel/006-sm.jpg",
          "md": "/photos/cristina-daniel/006-md.jpg",
          "lg": "/photos/cristina-daniel/006-lg.jpg"
        },
        "width": 5808,
        "height": 3872,
        "orientation": "landscape"
      }
    ]
  },
  "aaron-marta": {
    "couple": "Aaron & Marta",
    "images": [
      {
        "id": "aaron-marta/001",
        "couple": "aaron-marta",
        "variants": {
          "sm": "/photos/aaron-marta/001-sm.jpg",
          "md": "/photos/aaron-marta/001-md.jpg",
          "lg": "/photos/aaron-marta/001-lg.jpg"
        },
        "width": 7518,
        "height": 5015,
        "orientation": "landscape"
      },
      {
        "id": "aaron-marta/002",
        "couple": "aaron-marta",
        "variants": {
          "sm": "/photos/aaron-marta/002-sm.jpg",
          "md": "/photos/aaron-marta/002-md.jpg",
          "lg": "/photos/aaron-marta/002-lg.jpg"
        },
        "width": 5072,
        "height": 7101,
        "orientation": "portrait"
      },
      {
        "id": "aaron-marta/003",
        "couple": "aaron-marta",
        "variants": {
          "sm": "/photos/aaron-marta/003-sm.jpg",
          "md": "/photos/aaron-marta/003-md.jpg",
          "lg": "/photos/aaron-marta/003-lg.jpg"
        },
        "width": 4955,
        "height": 6937,
        "orientation": "portrait"
      }
    ]
  },
  "josep-eli": {
    "couple": "Elisabet & Josep",
    "images": [
      {
        "id": "josep-eli/001",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/001-sm.jpg",
          "md": "/photos/josep-eli/001-md.jpg",
          "lg": "/photos/josep-eli/001-lg.jpg"
        },
        "width": 3307,
        "height": 4960,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/002",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/002-sm.jpg",
          "md": "/photos/josep-eli/002-md.jpg",
          "lg": "/photos/josep-eli/002-lg.jpg"
        },
        "width": 5944,
        "height": 3963,
        "orientation": "landscape"
      },
      {
        "id": "josep-eli/003",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/003-sm.jpg",
          "md": "/photos/josep-eli/003-md.jpg",
          "lg": "/photos/josep-eli/003-lg.jpg"
        },
        "width": 1475,
        "height": 2623,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/004",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/004-sm.jpg",
          "md": "/photos/josep-eli/004-md.jpg",
          "lg": "/photos/josep-eli/004-lg.jpg"
        },
        "width": 2471,
        "height": 3706,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/005",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/005-sm.jpg",
          "md": "/photos/josep-eli/005-md.jpg",
          "lg": "/photos/josep-eli/005-lg.jpg"
        },
        "width": 3786,
        "height": 5678,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/006",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/006-sm.jpg",
          "md": "/photos/josep-eli/006-md.jpg",
          "lg": "/photos/josep-eli/006-lg.jpg"
        },
        "width": 3865,
        "height": 5797,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/007",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/007-sm.jpg",
          "md": "/photos/josep-eli/007-md.jpg",
          "lg": "/photos/josep-eli/007-lg.jpg"
        },
        "width": 1825,
        "height": 2555,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/008",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/008-sm.jpg",
          "md": "/photos/josep-eli/008-md.jpg",
          "lg": "/photos/josep-eli/008-lg.jpg"
        },
        "width": 3622,
        "height": 5432,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/009",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/009-sm.jpg",
          "md": "/photos/josep-eli/009-md.jpg",
          "lg": "/photos/josep-eli/009-lg.jpg"
        },
        "width": 2526,
        "height": 3789,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/010",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/010-sm.jpg",
          "md": "/photos/josep-eli/010-md.jpg",
          "lg": "/photos/josep-eli/010-lg.jpg"
        },
        "width": 3718,
        "height": 5577,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/011",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/011-sm.jpg",
          "md": "/photos/josep-eli/011-md.jpg",
          "lg": "/photos/josep-eli/011-lg.jpg"
        },
        "width": 3917,
        "height": 5875,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/012",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/012-sm.jpg",
          "md": "/photos/josep-eli/012-md.jpg",
          "lg": "/photos/josep-eli/012-lg.jpg"
        },
        "width": 2898,
        "height": 5152,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/013",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/013-sm.jpg",
          "md": "/photos/josep-eli/013-md.jpg",
          "lg": "/photos/josep-eli/013-lg.jpg"
        },
        "width": 4111,
        "height": 5755,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/014",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/014-sm.jpg",
          "md": "/photos/josep-eli/014-md.jpg",
          "lg": "/photos/josep-eli/014-lg.jpg"
        },
        "width": 3294,
        "height": 4937,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/015",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/015-sm.jpg",
          "md": "/photos/josep-eli/015-md.jpg",
          "lg": "/photos/josep-eli/015-lg.jpg"
        },
        "width": 2545,
        "height": 3817,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/016",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/016-sm.jpg",
          "md": "/photos/josep-eli/016-md.jpg",
          "lg": "/photos/josep-eli/016-lg.jpg"
        },
        "width": 4991,
        "height": 7483,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/017",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/017-sm.jpg",
          "md": "/photos/josep-eli/017-md.jpg",
          "lg": "/photos/josep-eli/017-lg.jpg"
        },
        "width": 5975,
        "height": 3983,
        "orientation": "landscape"
      },
      {
        "id": "josep-eli/018",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/018-sm.jpg",
          "md": "/photos/josep-eli/018-md.jpg",
          "lg": "/photos/josep-eli/018-lg.jpg"
        },
        "width": 3422,
        "height": 5131,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/019",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/019-sm.jpg",
          "md": "/photos/josep-eli/019-md.jpg",
          "lg": "/photos/josep-eli/019-lg.jpg"
        },
        "width": 3916,
        "height": 5482,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/020",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/020-sm.jpg",
          "md": "/photos/josep-eli/020-md.jpg",
          "lg": "/photos/josep-eli/020-lg.jpg"
        },
        "width": 3174,
        "height": 5643,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/021",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/021-sm.jpg",
          "md": "/photos/josep-eli/021-md.jpg",
          "lg": "/photos/josep-eli/021-lg.jpg"
        },
        "width": 2794,
        "height": 3911,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/022",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/022-sm.jpg",
          "md": "/photos/josep-eli/022-md.jpg",
          "lg": "/photos/josep-eli/022-lg.jpg"
        },
        "width": 3274,
        "height": 4907,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/023",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/023-sm.jpg",
          "md": "/photos/josep-eli/023-md.jpg",
          "lg": "/photos/josep-eli/023-lg.jpg"
        },
        "width": 3718,
        "height": 5577,
        "orientation": "portrait"
      },
      {
        "id": "josep-eli/024",
        "couple": "josep-eli",
        "variants": {
          "sm": "/photos/josep-eli/024-sm.jpg",
          "md": "/photos/josep-eli/024-md.jpg",
          "lg": "/photos/josep-eli/024-lg.jpg"
        },
        "width": 3437,
        "height": 5151,
        "orientation": "portrait"
      }
    ]
  },
  "idoya-pau": {
    "couple": "Idoya & Pau",
    "images": [
      {
        "id": "idoya-pau/001",
        "couple": "idoya-pau",
        "variants": {
          "sm": "/photos/idoya-pau/001-sm.jpg",
          "md": "/photos/idoya-pau/001-md.jpg",
          "lg": "/photos/idoya-pau/001-lg.jpg"
        },
        "width": 5221,
        "height": 7836,
        "orientation": "portrait"
      },
      {
        "id": "idoya-pau/002",
        "couple": "idoya-pau",
        "variants": {
          "sm": "/photos/idoya-pau/002-sm.jpg",
          "md": "/photos/idoya-pau/002-md.jpg",
          "lg": "/photos/idoya-pau/002-lg.jpg"
        },
        "width": 3002,
        "height": 5336,
        "orientation": "portrait"
      },
      {
        "id": "idoya-pau/003",
        "couple": "idoya-pau",
        "variants": {
          "sm": "/photos/idoya-pau/003-sm.jpg",
          "md": "/photos/idoya-pau/003-md.jpg",
          "lg": "/photos/idoya-pau/003-lg.jpg"
        },
        "width": 5285,
        "height": 7924,
        "orientation": "portrait"
      },
      {
        "id": "idoya-pau/004",
        "couple": "idoya-pau",
        "variants": {
          "sm": "/photos/idoya-pau/004-sm.jpg",
          "md": "/photos/idoya-pau/004-md.jpg",
          "lg": "/photos/idoya-pau/004-lg.jpg"
        },
        "width": 7663,
        "height": 5111,
        "orientation": "landscape"
      }
    ]
  },
  "elena-jordi": {
    "couple": "Elena & Jordi",
    "images": [
      {
        "id": "elena-jordi/001",
        "couple": "elena-jordi",
        "variants": {
          "sm": "/photos/elena-jordi/001-sm.jpg",
          "md": "/photos/elena-jordi/001-md.jpg",
          "lg": "/photos/elena-jordi/001-lg.jpg"
        },
        "width": 3969,
        "height": 5954,
        "orientation": "portrait"
      },
      {
        "id": "elena-jordi/002",
        "couple": "elena-jordi",
        "variants": {
          "sm": "/photos/elena-jordi/002-sm.jpg",
          "md": "/photos/elena-jordi/002-md.jpg",
          "lg": "/photos/elena-jordi/002-lg.jpg"
        },
        "width": 7515,
        "height": 5012,
        "orientation": "landscape"
      },
      {
        "id": "elena-jordi/003",
        "couple": "elena-jordi",
        "variants": {
          "sm": "/photos/elena-jordi/003-sm.jpg",
          "md": "/photos/elena-jordi/003-md.jpg",
          "lg": "/photos/elena-jordi/003-lg.jpg"
        },
        "width": 3778,
        "height": 5667,
        "orientation": "portrait"
      },
      {
        "id": "elena-jordi/004",
        "couple": "elena-jordi",
        "variants": {
          "sm": "/photos/elena-jordi/004-sm.jpg",
          "md": "/photos/elena-jordi/004-md.jpg",
          "lg": "/photos/elena-jordi/004-lg.jpg"
        },
        "width": 3628,
        "height": 5442,
        "orientation": "portrait"
      },
      {
        "id": "elena-jordi/005",
        "couple": "elena-jordi",
        "variants": {
          "sm": "/photos/elena-jordi/005-sm.jpg",
          "md": "/photos/elena-jordi/005-md.jpg",
          "lg": "/photos/elena-jordi/005-lg.jpg"
        },
        "width": 3569,
        "height": 5351,
        "orientation": "portrait"
      },
      {
        "id": "elena-jordi/006",
        "couple": "elena-jordi",
        "variants": {
          "sm": "/photos/elena-jordi/006-sm.jpg",
          "md": "/photos/elena-jordi/006-md.jpg",
          "lg": "/photos/elena-jordi/006-lg.jpg"
        },
        "width": 7880,
        "height": 5256,
        "orientation": "landscape"
      },
      {
        "id": "elena-jordi/007",
        "couple": "elena-jordi",
        "variants": {
          "sm": "/photos/elena-jordi/007-sm.jpg",
          "md": "/photos/elena-jordi/007-md.jpg",
          "lg": "/photos/elena-jordi/007-lg.jpg"
        },
        "width": 5278,
        "height": 5278,
        "orientation": "landscape"
      }
    ]
  },
  "javi-olaya": {
    "couple": "Javi & Olaya",
    "images": [
      {
        "id": "javi-olaya/001",
        "couple": "javi-olaya",
        "variants": {
          "sm": "/photos/javi-olaya/001-sm.jpg",
          "md": "/photos/javi-olaya/001-md.jpg",
          "lg": "/photos/javi-olaya/001-lg.jpg"
        },
        "width": 7149,
        "height": 5106,
        "orientation": "landscape"
      },
      {
        "id": "javi-olaya/002",
        "couple": "javi-olaya",
        "variants": {
          "sm": "/photos/javi-olaya/002-sm.jpg",
          "md": "/photos/javi-olaya/002-md.jpg",
          "lg": "/photos/javi-olaya/002-lg.jpg"
        },
        "width": 5195,
        "height": 7788,
        "orientation": "portrait"
      },
      {
        "id": "javi-olaya/003",
        "couple": "javi-olaya",
        "variants": {
          "sm": "/photos/javi-olaya/003-sm.jpg",
          "md": "/photos/javi-olaya/003-md.jpg",
          "lg": "/photos/javi-olaya/003-lg.jpg"
        },
        "width": 5037,
        "height": 7551,
        "orientation": "portrait"
      },
      {
        "id": "javi-olaya/004",
        "couple": "javi-olaya",
        "variants": {
          "sm": "/photos/javi-olaya/004-sm.jpg",
          "md": "/photos/javi-olaya/004-md.jpg",
          "lg": "/photos/javi-olaya/004-lg.jpg"
        },
        "width": 5163,
        "height": 7740,
        "orientation": "portrait"
      },
      {
        "id": "javi-olaya/005",
        "couple": "javi-olaya",
        "variants": {
          "sm": "/photos/javi-olaya/005-sm.jpg",
          "md": "/photos/javi-olaya/005-md.jpg",
          "lg": "/photos/javi-olaya/005-lg.jpg"
        },
        "width": 5163,
        "height": 7740,
        "orientation": "portrait"
      }
    ]
  },
  "jennifer-albert": {
    "couple": "Jennifer & Albert",
    "images": [
      {
        "id": "jennifer-albert/001",
        "couple": "jennifer-albert",
        "variants": {
          "sm": "/photos/jennifer-albert/001-sm.jpg",
          "md": "/photos/jennifer-albert/001-md.jpg",
          "lg": "/photos/jennifer-albert/001-lg.jpg"
        },
        "width": 6648,
        "height": 4434,
        "orientation": "landscape"
      }
    ]
  },
  "marta-adria": {
    "couple": "Marta & Adrià",
    "images": [
      {
        "id": "marta-adria/001",
        "couple": "marta-adria",
        "variants": {
          "sm": "/photos/marta-adria/001-sm.jpg",
          "md": "/photos/marta-adria/001-md.jpg",
          "lg": "/photos/marta-adria/001-lg.jpg"
        },
        "width": 3152,
        "height": 4725,
        "orientation": "portrait"
      },
      {
        "id": "marta-adria/002",
        "couple": "marta-adria",
        "variants": {
          "sm": "/photos/marta-adria/002-sm.jpg",
          "md": "/photos/marta-adria/002-md.jpg",
          "lg": "/photos/marta-adria/002-lg.jpg"
        },
        "width": 4042,
        "height": 4042,
        "orientation": "landscape"
      },
      {
        "id": "marta-adria/003",
        "couple": "marta-adria",
        "variants": {
          "sm": "/photos/marta-adria/003-sm.jpg",
          "md": "/photos/marta-adria/003-md.jpg",
          "lg": "/photos/marta-adria/003-lg.jpg"
        },
        "width": 4196,
        "height": 6291,
        "orientation": "portrait"
      },
      {
        "id": "marta-adria/004",
        "couple": "marta-adria",
        "variants": {
          "sm": "/photos/marta-adria/004-sm.jpg",
          "md": "/photos/marta-adria/004-md.jpg",
          "lg": "/photos/marta-adria/004-lg.jpg"
        },
        "width": 3161,
        "height": 4737,
        "orientation": "portrait"
      },
      {
        "id": "marta-adria/005",
        "couple": "marta-adria",
        "variants": {
          "sm": "/photos/marta-adria/005-sm.jpg",
          "md": "/photos/marta-adria/005-md.jpg",
          "lg": "/photos/marta-adria/005-lg.jpg"
        },
        "width": 2749,
        "height": 4082,
        "orientation": "portrait"
      },
      {
        "id": "marta-adria/006",
        "couple": "marta-adria",
        "variants": {
          "sm": "/photos/marta-adria/006-sm.jpg",
          "md": "/photos/marta-adria/006-md.jpg",
          "lg": "/photos/marta-adria/006-lg.jpg"
        },
        "width": 3164,
        "height": 4742,
        "orientation": "portrait"
      }
    ]
  },
  "generic": {
    "couple": null,
    "images": [
      {
        "id": "generic/001",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/001-sm.jpg",
          "md": "/photos/generic/001-md.jpg",
          "lg": "/photos/generic/001-lg.jpg"
        },
        "width": 4913,
        "height": 3509,
        "orientation": "landscape"
      },
      {
        "id": "generic/002",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/002-sm.jpg",
          "md": "/photos/generic/002-md.jpg",
          "lg": "/photos/generic/002-lg.jpg"
        },
        "width": 4000,
        "height": 6000,
        "orientation": "portrait"
      },
      {
        "id": "generic/003",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/003-sm.jpg",
          "md": "/photos/generic/003-md.jpg",
          "lg": "/photos/generic/003-lg.jpg"
        },
        "width": 5510,
        "height": 3673,
        "orientation": "landscape"
      },
      {
        "id": "generic/004",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/004-sm.jpg",
          "md": "/photos/generic/004-md.jpg",
          "lg": "/photos/generic/004-lg.jpg"
        },
        "width": 4000,
        "height": 6000,
        "orientation": "portrait"
      },
      {
        "id": "generic/005",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/005-sm.jpg",
          "md": "/photos/generic/005-md.jpg",
          "lg": "/photos/generic/005-lg.jpg"
        },
        "width": 5744,
        "height": 3829,
        "orientation": "landscape"
      },
      {
        "id": "generic/006",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/006-sm.jpg",
          "md": "/photos/generic/006-md.jpg",
          "lg": "/photos/generic/006-lg.jpg"
        },
        "width": 5525,
        "height": 3062,
        "orientation": "landscape"
      },
      {
        "id": "generic/007",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/007-sm.jpg",
          "md": "/photos/generic/007-md.jpg",
          "lg": "/photos/generic/007-lg.jpg"
        },
        "width": 960,
        "height": 686,
        "orientation": "landscape"
      },
      {
        "id": "generic/008",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/008-sm.jpg",
          "md": "/photos/generic/008-md.jpg",
          "lg": "/photos/generic/008-lg.jpg"
        },
        "width": 960,
        "height": 640,
        "orientation": "landscape"
      },
      {
        "id": "generic/009",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/009-sm.jpg",
          "md": "/photos/generic/009-md.jpg",
          "lg": "/photos/generic/009-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      },
      {
        "id": "generic/010",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/010-sm.jpg",
          "md": "/photos/generic/010-md.jpg",
          "lg": "/photos/generic/010-lg.jpg"
        },
        "width": 960,
        "height": 640,
        "orientation": "landscape"
      },
      {
        "id": "generic/011",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/011-sm.jpg",
          "md": "/photos/generic/011-md.jpg",
          "lg": "/photos/generic/011-lg.jpg"
        },
        "width": 4567,
        "height": 3045,
        "orientation": "landscape"
      },
      {
        "id": "generic/012",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/012-sm.jpg",
          "md": "/photos/generic/012-md.jpg",
          "lg": "/photos/generic/012-lg.jpg"
        },
        "width": 2869,
        "height": 4016,
        "orientation": "portrait"
      },
      {
        "id": "generic/013",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/013-sm.jpg",
          "md": "/photos/generic/013-md.jpg",
          "lg": "/photos/generic/013-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      },
      {
        "id": "generic/014",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/014-sm.jpg",
          "md": "/photos/generic/014-md.jpg",
          "lg": "/photos/generic/014-lg.jpg"
        },
        "width": 686,
        "height": 960,
        "orientation": "portrait"
      },
      {
        "id": "generic/015",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/015-sm.jpg",
          "md": "/photos/generic/015-md.jpg",
          "lg": "/photos/generic/015-lg.jpg"
        },
        "width": 2857,
        "height": 4000,
        "orientation": "portrait"
      },
      {
        "id": "generic/016",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/016-sm.jpg",
          "md": "/photos/generic/016-md.jpg",
          "lg": "/photos/generic/016-lg.jpg"
        },
        "width": 5080,
        "height": 3387,
        "orientation": "landscape"
      },
      {
        "id": "generic/017",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/017-sm.jpg",
          "md": "/photos/generic/017-md.jpg",
          "lg": "/photos/generic/017-lg.jpg"
        },
        "width": 5187,
        "height": 3458,
        "orientation": "landscape"
      },
      {
        "id": "generic/018",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/018-sm.jpg",
          "md": "/photos/generic/018-md.jpg",
          "lg": "/photos/generic/018-lg.jpg"
        },
        "width": 3466,
        "height": 4852,
        "orientation": "portrait"
      },
      {
        "id": "generic/019",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/019-sm.jpg",
          "md": "/photos/generic/019-md.jpg",
          "lg": "/photos/generic/019-lg.jpg"
        },
        "width": 5397,
        "height": 3598,
        "orientation": "landscape"
      },
      {
        "id": "generic/020",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/020-sm.jpg",
          "md": "/photos/generic/020-md.jpg",
          "lg": "/photos/generic/020-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      },
      {
        "id": "generic/021",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/021-sm.jpg",
          "md": "/photos/generic/021-md.jpg",
          "lg": "/photos/generic/021-lg.jpg"
        },
        "width": 5927,
        "height": 3951,
        "orientation": "landscape"
      },
      {
        "id": "generic/022",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/022-sm.jpg",
          "md": "/photos/generic/022-md.jpg",
          "lg": "/photos/generic/022-lg.jpg"
        },
        "width": 2666,
        "height": 3732,
        "orientation": "portrait"
      },
      {
        "id": "generic/023",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/023-sm.jpg",
          "md": "/photos/generic/023-md.jpg",
          "lg": "/photos/generic/023-lg.jpg"
        },
        "width": 2481,
        "height": 3473,
        "orientation": "portrait"
      },
      {
        "id": "generic/024",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/024-sm.jpg",
          "md": "/photos/generic/024-md.jpg",
          "lg": "/photos/generic/024-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      },
      {
        "id": "generic/025",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/025-sm.jpg",
          "md": "/photos/generic/025-md.jpg",
          "lg": "/photos/generic/025-lg.jpg"
        },
        "width": 3329,
        "height": 4660,
        "orientation": "portrait"
      },
      {
        "id": "generic/026",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/026-sm.jpg",
          "md": "/photos/generic/026-md.jpg",
          "lg": "/photos/generic/026-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      },
      {
        "id": "generic/027",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/027-sm.jpg",
          "md": "/photos/generic/027-md.jpg",
          "lg": "/photos/generic/027-lg.jpg"
        },
        "width": 4000,
        "height": 6000,
        "orientation": "portrait"
      },
      {
        "id": "generic/028",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/028-sm.jpg",
          "md": "/photos/generic/028-md.jpg",
          "lg": "/photos/generic/028-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      },
      {
        "id": "generic/029",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/029-sm.jpg",
          "md": "/photos/generic/029-md.jpg",
          "lg": "/photos/generic/029-lg.jpg"
        },
        "width": 1537,
        "height": 2152,
        "orientation": "portrait"
      },
      {
        "id": "generic/030",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/030-sm.jpg",
          "md": "/photos/generic/030-md.jpg",
          "lg": "/photos/generic/030-lg.jpg"
        },
        "width": 960,
        "height": 640,
        "orientation": "landscape"
      },
      {
        "id": "generic/031",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/031-sm.jpg",
          "md": "/photos/generic/031-md.jpg",
          "lg": "/photos/generic/031-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      },
      {
        "id": "generic/032",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/032-sm.jpg",
          "md": "/photos/generic/032-md.jpg",
          "lg": "/photos/generic/032-lg.jpg"
        },
        "width": 3909,
        "height": 5473,
        "orientation": "portrait"
      },
      {
        "id": "generic/033",
        "couple": "generic",
        "variants": {
          "sm": "/photos/generic/033-sm.jpg",
          "md": "/photos/generic/033-md.jpg",
          "lg": "/photos/generic/033-lg.jpg"
        },
        "width": 6000,
        "height": 4000,
        "orientation": "landscape"
      }
    ]
  }
};
